data_collection_name: agent
feedback_collection_name: feedback

directory: lw_db
k: 3
data_path: data
md5_hex_store: md5.text
allow_knowledge_file_type: ["txt", "pdf", "csv"]

chunk_size: 2000
chunk_overlap: 20
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
